[mongodb]
; mongodb.anuragaws.shop
local 
[redis]
; redis.anuragaws.shop
local
[mysql]
; mysql.anuragaws.shop
local
[rabbitmq]
; rabbitmq.anuragaws.shop
local

[cart]
; cart.anuragaws.shop
local

[catalogue]
; catalogue.anuragaws.shop
local

[user]
; user.anuragaws.shop
local

[shipping]
; shipping.anuragaws.shop
local

[payment]
; payment.anuragaws.shop
local

[frontend]
; frontend.anuragaws.shop
local

[backend]
; backend.anuragaws.shop
local

[all:vars]
ansible_user=ec2-user
ansible_password="{{ lookup('amazon.aws.aws_ssm', '/roboshop/shh/loginpass', region='us-east-1', decrypt=True ) }}"
;ansible_password=DevOps321
; [local]
; localhost 