- name: setup app
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: setup python 
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml
- name: Install uwsgi python package
  ansible.builtin.pip:
    name: uwsgi
    executable: pip3

- name: systemd system 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml
